env:
  DUBBO_REF: master
jobs:
  build-dubbo:
    outputs:
      cache-hit: ${{ steps.dubbocache.outputs.cache-hit }}
      commit_id: ${{ steps.git-checker.outputs.commit_id }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
      with:
        ref: ${{env.DUBBO_REF}}
        repository: apache/dubbo
    - continue-on-error: true
      id: git-checker
      name: Get commit id and dubbo version
      run: '#compare dubbo commit id

        last_commit_id=`git log --format="%H" -n 1`

        echo "::set-output name=commit_id::$last_commit_id"

        echo "commit_id: $last_commit_id"

        # Calculate Dubbo Version

        REVISION=`awk ''/<revision>[^<]+<\/revision>/{gsub(/<revision>|<\/revision>/,"",$1);print
        $1;exit;}'' pom.xml`

        mkdir dubbo-version

        echo $REVISION > dubbo-version/dubbo-version

        echo "dubbo version: $REVISION"

        '
    - continue-on-error: true
      name: Upload Dubbo version
      uses: actions/upload-artifact@v2
      with:
        name: dubbo-version
        path: dubbo-version
    - continue-on-error: true
      id: dubbocache
      name: Dubbo cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dubbo-snapshot-${{steps.git-checker.outputs.commit_id}}
        path: ~/.m2/repository/org/apache/dubbo
    - continue-on-error: true
      if: steps.dubbocache.outputs.cache-hit != 'true'
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dubbo-${{env.DUBBO_REF}}-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-dubbo-${{env.DUBBO_REF}}-maven-

          '
    - continue-on-error: true
      if: steps.dubbocache.outputs.cache-hit != 'true'
      name: Set up JDK 8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - continue-on-error: true
      if: steps.dubbocache.outputs.cache-hit != 'true'
      name: Build dubbo
      run: './mvnw -U --batch-mode --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
        clean install -Dmaven.test.skip=true -Dmaven.test.skip.exec=true

        '
    strategy:
      fail-fast: false
  build-dubbo-spring-boot:
    needs:
    - build-dubbo
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dubbo-spring-boot-maven-${{ hashFiles('**/pom.xml')
          }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-dubbo-spring-boot-maven-

          '
    - continue-on-error: true
      name: Dubbo cache
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-dubbo-snapshot-${{needs.build-dubbo.outputs.commit_id}}
        path: ~/.m2/repository/org/apache/dubbo
    - continue-on-error: true
      name: Set up JDK ${{matrix.java}}
      uses: actions/setup-java@v1
      with:
        java-version: ${{matrix.java}}
    - continue-on-error: true
      name: Build dubbo-spring-boot
      run: './mvnw -U --batch-mode --no-transfer-progress -Dmaven.wagon.http.retryHandler.count=3
        clean package

        '
    - continue-on-error: true
      name: Codecov
      run: bash <(curl -s https://codecov.io/bash)
    strategy:
      fail-fast: false
      matrix:
        java:
        - 8
        - 11
name: Dubbo 2
on:
  repository_dispatch:
    types: trigger-ga___dubbo-2.yml
